### ISSUE TITLE
Filtri, ne abbiamo?

### ISSUE THREAD

**Issue by Lollerix** [Databasers/OtticaCrisci#22]
Come li implementiamo i filtri? A livello sql o dobbiamo filtrare il risultato dopo?
Spero e prego Crisci che sta roba la vogliamo risolvere in SQL.

**Comment by 00Joshua** [comment]
Potremmo implementarli in Ajax, chiamando asincronamente la Servlet
I filtri vengono passati ad una funzione JavaScript che chiama il server passandogli i filtri come parametri e, quando risponde, un handler refresha la pagina inserendo solo quelli restituiti
Non so se sia implementabile completamente dato che, almeno nelle slide, parlava di risposte Ajax in XML, quindi non saprei come passare arrayList di Frame

Anyway, nel caso non funzionasse possiamo anche solo inviare al server i filtri e lui risponde, tutto sincrono

Preferisco la prima opzione, dato che Ajax dobbiamo inserirlo per forza nel progetto
