### ISSUE TITLE
Pagina Carrello

### ISSUE THREAD

**Issue by Lollerix** [Databasers/OtticaCrisci#23]
Servirebbe la lista dei prodotti per la pagina del carrello. Potresti fare in modo che magari il manager la restituisca o qualcosa del genere?

**Comment by 00Joshua** [comment]
Il carrello è in sessione
Puoi prendere tutti i valori direttamente, solo che per aggiungere e cancellare se lo vede la servlet
Anche per il checkout se lo vede la servlet
